version: '3.8'

services:
  php-fpm:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php-fpm